// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCDF-HED2RzcaXcArRhxAWL9mWasQhNE8',
    appId: '1:4208989468:web:d0f367482afc4cb29ad6d9',
    messagingSenderId: '4208989468',
    projectId: 'bailongo-f3384',
    authDomain: 'bailongo-f3384.firebaseapp.com',
    storageBucket: 'bailongo-f3384.firebasestorage.app',
    measurementId: 'G-GBW7NSB9GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp4BzwMJ9O7S9rDVP_VMV3NHAx-aR_bzo',
    appId: '1:4208989468:android:148d4fdd5f3b62199ad6d9',
    messagingSenderId: '4208989468',
    projectId: 'bailongo-f3384',
    storageBucket: 'bailongo-f3384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJQYV-iXa4Belbd_t_Lh9_55H6mqYtICI',
    appId: '1:4208989468:ios:15b5fd5fe0589d479ad6d9',
    messagingSenderId: '4208989468',
    projectId: 'bailongo-f3384',
    storageBucket: 'bailongo-f3384.firebasestorage.app',
    iosBundleId: 'com.bailongo.bailongo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJQYV-iXa4Belbd_t_Lh9_55H6mqYtICI',
    appId: '1:4208989468:ios:15b5fd5fe0589d479ad6d9',
    messagingSenderId: '4208989468',
    projectId: 'bailongo-f3384',
    storageBucket: 'bailongo-f3384.firebasestorage.app',
    iosBundleId: 'com.bailongo.bailongo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCDF-HED2RzcaXcArRhxAWL9mWasQhNE8',
    appId: '1:4208989468:web:cbd3347a92d0b2579ad6d9',
    messagingSenderId: '4208989468',
    projectId: 'bailongo-f3384',
    authDomain: 'bailongo-f3384.firebaseapp.com',
    storageBucket: 'bailongo-f3384.firebasestorage.app',
    measurementId: 'G-S8PSCH03LM',
  );
}
